export default {
    oneClubs: require('./1Clubs.png'),
    twoClubs: require('./2Clubs.png'),
    threeClubs: require('./3Clubs.png'),
    fourClubs: require('./4Clubs.png'),
    fiveClubs: require('./5Clubs.png'),
    sixClubs: require('./6Clubs.png'),
    sevenClubs: require('./7Clubs.png'),
    eightClubs: require('./8Clubs.png'),
    nineClubs: require('./9Clubs.png'),
    tenClubs: require('./10Clubs.png'),
    JClubs: require('./10JClubs.png'),
    QClubs: require('./10QClubs.png'),
    KClubs: require('./10KClubs.png'),

    oneDiamonds: require('./1Diamonds.png'),
    twoDiamonds: require('./2Diamonds.png'),
    threeDiamonds: require('./3Diamonds.png'),
    fourDiamonds: require('./4Diamonds.png'),
    fiveDiamonds: require('./5Diamonds.png'),
    sixDiamonds: require('./6Diamonds.png'),
    sevenDiamonds: require('./7Diamonds.png'),
    eightDiamonds: require('./8Diamonds.png'),
    nineDiamonds: require('./9Diamonds.png'),
    tenDiamonds: require('./10Diamonds.png'),
    JDiamonds: require('./10JDiamonds.png'),
    QDiamonds: require('./10QDiamonds.png'),
    KDiamonds: require('./10KDiamonds.png'),

    oneHearts: require('./1Hearts.png'),
    twoHearts: require('./2Hearts.png'),
    threeHearts: require('./3Hearts.png'),
    fourHearts: require('./4Hearts.png'),
    fiveHearts: require('./5Hearts.png'),
    sixHearts: require('./6Hearts.png'),
    sevenHearts: require('./7Hearts.png'),
    eightHearts: require('./8Hearts.png'),
    nineHearts: require('./9Hearts.png'),
    tenHearts: require('./10Hearts.png'),
    JHearts: require('./10JHearts.png'),
    QHearts: require('./10QHearts.png'),
    KHearts: require('./10KHearts.png'),

    oneSpades: require('./1Spades.png'),
    twoSpades: require('./2Spades.png'),
    threeSpades: require('./3Spades.png'),
    fourSpades: require('./4Spades.png'),
    fiveSpades: require('./5Spades.png'),
    sixSpades: require('./6Spades.png'),
    sevenSpades: require('./7Spades.png'),
    eightSpades: require('./8Spades.png'),
    nineSpades: require('./9Spades.png'),
    tenSpades: require('./10Spades.png'),
    JSpades: require('./10JSpades.png'),
    QSpades: require('./10QSpades.png'),
    KSpades: require('./10KSpades.png'),

    back: require('./back.png')
}